data:
  class_path: run_event_detect.NerDataModule
  init_args:
    data_dir: data
    predict_data: validation
    batch_size: 32
    num_workers: 16
    tagset_path: globalise/tagsets/glb_events.json
    pretrained_model: emanjavacas/GysBERT-v2
model:
  class_path: run_event_detect.NERModel
  init_args:
    learning_rate: 5.0e-05
    freeze_model_params: false